######################################################################
# Automatically generated by qmake (2.01a) Fr Jun 29 21:27:23 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += imageviewer.h
FORMS += imageviewer.ui
SOURCES += imageviewer.cpp main.cpp
